contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #eisca channel"
    url: https://nfcore.slack.com/channels/eisca
    about: Discussion about the nf-core/eisca pipeline
